### ISSUE TITLE
Exonization of TE 

### ISSUE THREAD

**Issue by bshim181** [twlab/TEProf2Paper#13]
Hello, 

I am aware that TEProf2 identifies TE-gene chimeric transcripts where TEs are mainly serving as promoters. I was wondering if TEProf2 has the capacity to identify transcripts where TEs are serving as cassette exons or inserted in to introns and then transcribed as the form of retained intron transcripts. Thank you!

**Comment by nakul2234** [comment]
Hello, this is a great research question, but this pipeline is focused on TE-gene chimeras from promoters, and it cannot be easily adapted to allow for looking at exonization or intron retention events. The field is moving fast, so hopefully that gets developed soon!

**Comment by bshim181** [comment]
Thank you!
