### ISSUE TITLE
How to visualize the candidate TE-gene transcripts

### ISSUE THREAD

**Issue by Bio-Ting** [twlab/TEProf2Paper#15]
Hello, 

I was wondering how to visualize a candidate TE-gene transcripts, just like you showed in the  paper ?
<img width="928" alt="image" src="https://github.com/twlab/TEProf2Paper/assets/70944124/293d26d7-5f5d-4fc6-bdc6-b6ba668532a6">

Could you please share the code ?
Thank you !

**Comment by nakul2234** [comment]
Hello,

This is visualized using the WashU Epigenome Browser: https://epigenomegateway.wustl.edu/

The pipeline creates a *refbed* file. This can be visualized by processing it using the following instructions: https://eg.readthedocs.io/en/latest/tracks.html#refbed

-Nakul

**Comment by Bio-Ting** [comment]
Thank you very much !
