### ISSUE TITLE
no out_put in rmskhg38_annotate_gtf_update_test_tpm.py process

### ISSUE THREAD

**Issue by mechealeth** [twlab/TEProf2Paper#3]
Hi ，I am new to TEanalysis but i am keen to learn more about it . I would like to apply TEProf2 to analysis my data .  
My input data preprocess with the following command:
##align with STAR
STAR --genomeDir Path/to/genome_index --readFilesIn /Path/to/RNA.fq.gz --outFileNamePrefix rep1 --sjdbScore 2 --runThreadN 8 --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --winAnchorMultimapNmax 100 --outFilterMultimapNmax 100
## filter and assemble
samtools view -q 255 -h rnaseq.fastqAligned.sortedByCoord.out.bam | stringtie - -o rnaseq.fastqAligned.sortedByCoord.out.gtf -m 100 -c 1
##then annotate gtf
rmskhg38_annotate_gtf_update_test_tpm.py <gtffile> <argumentfile.txt>*
In this step, all the path in argument.txt  were all correct. there are no error in this teps but the outputfiles were all empty.
I also using samtool view -bS /sort to process the bam file before filter and assemble but i still got the empy output files without error.

so I would like to ask for help or any advices?

thanks
chen

**Comment by nakul2234** [comment]
Hello chen,

Thank you for using our pipeline! If you could please show me a sample of your gtf file to see what the format is? In addition, in your alignment, did you run it with the following parameters: `--outSAMattributes NH HI NM MD AS XS`. The `XS` tag is needed for stringtie to properly do the assembly with spliced transcripts. 

-Nakul

**Comment by mechealeth** [comment]
> Hello chen,
> 
> Thank you for using our pipeline! If you could please show me a sample of your gtf file to see what the format is? In addition, in your alignment, did you run it with the following parameters: `--outSAMattributes NH HI NM MD AS XS`. The `XS` tag is needed for stringtie to properly do the assembly with spliced transcripts.
> 
> -Nakul

**Comment by mechealeth** [comment]
> > Hello chen,
> > Thank you for using our pipeline! If you could please show me a sample of your gtf file to see what the format is? In addition, in your alignment, did you run it with the following parameters: `--outSAMattributes NH HI NM MD AS XS`. The `XS` tag is needed for stringtie to properly do the assembly with spliced transcripts.
> > -Nakul

Hi Nakul,
thanks for you help, it turn out that adding `--outSAMattributes NH HI NM MD AS XS` in my alignment process sovled my problem.
thanks a lot
chen
