### ISSUE TITLE
no '.stats' out put in step5--Calculate Read Information

### ISSUE THREAD

**Issue by mechealeth** [twlab/TEProf2Paper#7]
Hi,
I used ./filterreadcommands.txt to run the command but there are no '.stats' files outut, the result show as follow:

`./filterreadcommands.txt: line 1: ./filterreadstats/MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.stats: No such file or directory
./filterreadcommands.txt: line 2: ./filterreadstats/MIR_38707752_ACTN4_intron_5_ACTN4_exon_7_38647670--C2NEA-6c5ac35dae_c.stats: No such file or directory
./filterreadcommands.txt: line 3: ./filterreadstats/MIRc_189863925_TP63_intron_2_TP63_exon_4_189789660--C2NEA-75b63f12f5_c.stats: No such file or directory
./filterreadcommands.txt: line 4: ./filterreadstats/MIRb_77482007_SEPT9_intron_3_SEPT9_exon_5_77281410--C2NEA-2b309823f7_c.stats: No such file or directory
./filterreadcommands.txt: line 5: ./filterreadstats/AluSx_170359313_SKIL_intron_1_SKIL_exon_3_170357726--C2NEA-29cd8ee3ce_c.stats: No such file or directory
./filterreadcommands.txt: line 6: ./filterreadstats/MIRb_32221596_None_None_None_EIF3I_exon_1_32222370--C2NEA-242e0f38cd_c.stats: No such file or directory
./filterreadcommands.txt: line 7: ./filterreadstats/L1PA2_116718497_MET_intron_2_MET_exon_3_116672392--C2NEA-1380aee480_c.stats: No such file or directory
./filterreadcommands.txt: line 8: ./filterreadstats/AluSp_70404720_CTTN_intron_1_CTTN_exon_3_70398404--C2NEA-64eb5edaf6_c.stats: No such file or directory
`
and my input filterreadcommands.txt show as follow:

`samtools view -q 255 -h -f 2 -F 4 /home/xxxx/TEProF2/data/bam/test/C2NEA-29cd8ee3ce_c.bam chr5:151660096-151688326 > MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.sam ; samtools view -q 255 -f 2 -F 4 /home/xxxx/TEProF2/data/bam/test/C2NEA-29cd8ee3ce_c.bam chr5:151687169-151687326 | cut -f1  | sort | uniq > MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_cIDs.txt ; cat <(samtools view -H MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.sam) <(grep -w -F -f MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_cIDs.txt MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.sam) | samtools sort -n -m 1G - | bedtools bamtobed -bedpe -i stdin 2>/dev/null | /home/xxxx/TEProF2/TEProf2Paper-main/bin/rmsk_annotate_bedpe_speed.py chr5,151687169,151687326 151671573,151671694,151667467,151667600,151673129,151673216,151666510,151667466,151676132,151676201,151666361,151666509,151686865,151687165,151676202,151686864,151669664,151669784,151667601,151669663,151663600,151664086,151673217,151674611,151671695,151673128,151674675,151676131,151669785,151671572,151664087,151664235,151674612,151674674,151664236,151666360,151661096,151663599 - None 1 > ./filterreadstats/MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.stats ; rm MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_c.sam ; rm MIR3_151687169_None_None_None_SPARC_exon_1_151661096--C2NEA-29cd8ee3ce_cIDs.txt`

I had no idea how to solve this problem, so i would like to ask for help !

many thanks
chen

**Comment by nakul2234** [comment]
Hello,

Sorry for the delayed response, was out of the country. Can you install `bedtools` on conda and then run step 5 again? 

Best,
Nakul

**Comment by mechealeth** [comment]
Many thanks !!!
