### ISSUE TITLE
UnsatisfiableError during conda installation

### ISSUE THREAD

**Issue by ChristianRohde** [twlab/TEProf2Paper#8]
Hi, I am using conda version 23.5.0. I downloaded the script TEProf2.yml from github and try to run it as recommended:

```
conda env create -f TEProf2.yml
```
Unfortunatly I run into a lot of conflicts and finally UnsatisfiableError. In the end I get the message 'Your installed version is: 2.28' but I cannot activate the enviroment since it has not been created. 

Please have a look at the output from conda attached. How can we solve these issues?

Best,
Christian
[TEProf2_conda_issue.txt](https://github.com/twlab/TEProf2Paper/files/11722697/TEProf2_conda_issue.txt)

**Comment by nakul2234** [comment]
Hello Christian,

I had used 22.9.0 version to create the .yml, but I am not sure if it will work in the most up-to-date version. I will see if it will work on a clean install of 23.5.0. If not, I may have to make the .yml again. 

Best,
Nakul

**Comment by nakul2234** [comment]
Hello @ChristianRohde,

Could you please try again using the following YML file: https://wangftp.wustl.edu/~nshah/ucsf/TCGA33Download/TEProf2Paper.yml

Best,
Nakul

**Comment by ChristianRohde** [comment]
> Hello @ChristianRohde,
> 
> Could you please try again using the following YML file: https://wangftp.wustl.edu/~nshah/ucsf/TCGA33Download/TEProf2Paper.yml
> 
> Best, Nakul

yes, this one worked!. Thank you very much
